name: flutter_secure_storage
description: A Flutter plugin for securely storing sensitive data using encrypted storage.
publish_to: none
version: 10.0.0-beta.4
repository: https://github.com/mogol/flutter_secure_storage/tree/develop/flutter_secure_storage

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        default_package: flutter_secure_storage_darwin
      macos:
        default_package: flutter_secure_storage_darwin
      linux:
        default_package: flutter_secure_storage_linux
      web:
        default_package: flutter_secure_storage_web
      windows:
        default_package: flutter_secure_storage_windows

dependencies:
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # implementation constraints as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # https://github.com/flutter/flutter/issues/46264
  flutter_secure_storage_linux:
    git: https://github.com/kumsumit/flutter_secure_storage_linux.git
  flutter_secure_storage_darwin:
    git: https://github.com/kumsumit/flutter_secure_storage_darwin.git
  flutter_secure_storage_platform_interface:
    git: https://github.com/kumsumit/flutter_secure_storage_platform_interface.git
  flutter_secure_storage_web:
    git: https://github.com/kumsumit/flutter_secure_storage_web.git
  flutter_secure_storage_windows:
    git: https://github.com/kumsumit/flutter_secure_storage_windows.git
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
  very_good_analysis: ^7.0.0

# We need to manually declare supported platforms, because pub.dev won't find them.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
